[
  {
    id: 0,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/ШЕЙКА_СВИНАЯ.webp",
    name: "Свиная шейка",
    description:
      "Сочный и ароматный шашлык из свиной шейки, приготовленный на углях с нежными специями",
    price: "440",
    weight: "шп",
  },
  {
    id: 1,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/МЯКОТЬ_БАРАНИНА.webp",
    name: "Мякоть баранина",
    description:
      "Изысканный шашлык из нежной мякоти баранины, приправленный ароматными специями и обжаренный на углях",
    price: "640",
    weight: "шп",
  },
  {
    id: 2,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/БЕДРО_КУРИНЫЕ.webp",
    name: "Куриное бедро",
    description:
      "Сочный шашлык с куриным бедром, приготовленный с травами и ароматными специями",
    price: "350",
    weight: "шп",
  },
  {
    id: 3,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/РЕБРА_СВИНИНА.webp",
    name: "Свиные ребра",
    description:
      "Пикантный шашлык из свиных рёбер с пряными приправами и аппетитной хрустящей коркой",
    price: "400",
    weight: "шп",
  },
  {
    id: 4,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/ФИЛЕ_ТЕЛЯТИНЫ.webp",
    name: "Филе телятины",
    description:
      "Нежный шашлык из филе телятины, приправленный уникальными специями для неповторимого вкуса",
    price: "640",
    weight: "шп",
  },
  {
    id: 5,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/КАРЕ_ЯГНЕНКА.webp",
    name: "Корейка ягненка",
    description:
      "Эксклюзивный шашлык из корейки ягненка с насыщенными восточными пряностями и аппетитной коркой",
    price: "650",
    weight: "шп",
  },
  {
    id: 6,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/РЕБРА_БАРАНИНА.webp",
    name: "Ребра баранина",
    description:
      "Ароматный шашлык из сочных рёбер баранины, пропитанный пряными специями и обжаренный на углях",
    price: "500",
    weight: "шп",
  },
  {
    id: 7,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/КУРИНЫЕ_КРЫЛЬЯ.webp",
    name: "Куриные крылья",
    description:
      "Сочные куриные крылья, обжаренные до золотистой хрустящей корки, с аппетитными приправами",
    price: "300",
    weight: "шп",
  },
  {
    id: 8,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/ФИЛЕ_КУРИНОЕ.webp",
    name: "Куриное филе",
    description:
      "Нежный шашлык из куриного филе с ароматными специями и золотистой коркой на углях",
    price: "370",
    weight: "шп",
  },
  {
    id: 9,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/КРЫЛЬЯ_БАРБЕКЮ.webp",
    name: "Крылья барбекю",
    description:
      "Крылья барбекю – сочные и ароматные, обжаренные до идеальной хрустящей корки с барбекю-соусом",
    price: "320",
    weight: "шп",
  },
  {
    id: 10,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/БЕДРО_ИНДЕЙКИ.webp",
    name: "Бедро индейки",
    description:
      "Нежный шашлык из индейки, приготовленное с травами и ароматными специями для непередаваемого вкуса",
    price: "450",
    weight: "шп",
  },
  {
    id: 11,
    category: "2",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/СЕРДЦЕ_ИНДЕЙКИ.webp",
    name: "Сердце индейки",
    description:
      "Утонченный шашлык из сердец индейки, пряно приправленный и приготовленный с искусством",
    price: "400",
    weight: "шп",
  },
  {
    id: 12,
    category: "3",
    categoryName: "ШАУРМА",
    img: "images/menu_item/shawarma/ШАУРМА_КУРИЦА.webp",
    name: "C курицей",
    description:
      "Аппетитная шаурма с нежным куриным мясом и ароматными специями в пышном лаваше",
    price: "200",
    weight: "шт",
  },
  {
    id: 13,
    category: "3",
    categoryName: "ШАУРМА",
    img: "images/menu_item/shawarma/ШАУРМА_СВИНИНА.webp",
    name: "Cо свининой",
    description:
      "Изысканная шаурма с ароматной свининой, специями и сочными овощами в лаваше",
    price: "250",
    weight: "шт",
  },
  {
    id: 14,
    category: "3",
    categoryName: "ШАУРМА",
    img: "images/menu_item/shawarma/ШАУРМА_СВИНИНА.webp",
    name: "C говядиной",
    description:
      "Шаурма с нежной говядиной, оригинальными специями и сочными овощами в лаваше",
    price: "300",
    weight: "шт",
  },
  {
    id: 15,
    category: "3",
    categoryName: "ШАУРМА",
    img: "images/menu_item/shawarma/ШАУРМА_СВИНИНА.webp",
    name: "C бараниной",
    description:
      "Ароматная шаурма с нежной бараниной, приправленная специями и укутанная в пышный лаваш",
    price: "330",
    weight: "шт",
  },
  {
    id: 16,
    category: "3",
    categoryName: "ШАУРМА",
    img: "images/menu_item/shawarma/ШАУРМА_КУРИЦА.webp",
    name: "C индейкой",
    description:
      "Шаурма с нежным мясом индейки, ароматными специями и свежими овощами в лаваше",
    price: "300",
    weight: "шт",
  },
  {
    id: 17,
    category: "4",
    categoryName: "ЛЮЛЯ-КЕБАБ",
    img: "images/menu_item/lula_kebab/ГОВЯДИНА.webp",
    name: "Говядина",
    description:
      "Изысканный люля-кебаб с нежной говядиной и оригинальными специями, приготовленный с любовью",
    price: "320",
    weight: "шп",
  },
  {
    id: 18,
    category: "4",
    categoryName: "ЛЮЛЯ-КЕБАБ",
    img: "images/menu_item/lula_kebab/БАРАНИНА.webp",
    name: "Баранина",
    description:
      "Ароматный люля-кебаб с нежной бараниной и пряными специями, приготовленный с искусством",
    price: "320",
    weight: "шп",
  },
  {
    id: 19,
    category: "4",
    categoryName: "ЛЮЛЯ-КЕБАБ",
    img: "images/menu_item/lula_kebab/Люля_Курица.webp",
    name: "Из курицы",
    description:
      "Легкий и аппетитный люля-кебаб из нежного куриного мяса, обогащенный специями",
    price: "280",
    weight: "шп",
  },
  {
    id: 20,
    category: "4",
    categoryName: "ЛЮЛЯ-КЕБАБ",
    img: "images/menu_item/lula_kebab/СВИНИНА.webp",
    name: "Свинина",
    description:
      "Сочный люля-кебаб с нежной свининой и ароматными специями для истинных гурманов",
    price: "300",
    weight: "шп",
  },
  {
    id: 21,
    category: "5",
    categoryName: "РЫБА",
    img: "images/menu_item/fish/ДОРАДО.webp",
    name: "Дорадо",
    description:
      "Дорадо на гриле – свежая рыба с идеальной хрустящей коркой и ароматом моря",
    price: "699",
    weight: "шт",
  },
  {
    id: 22,
    category: "5",
    categoryName: "РЫБА",
    img: "images/menu_item/fish/СИБАС.webp",
    name: "Сибас",
    description:
      "Сибас на гриле - изысканно приготовленная свежая рыба с ароматом моря и нежной текстурой",
    price: "699",
    weight: "шт",
  },
  {
    id: 23,
    category: "5",
    categoryName: "РЫБА",
    img: "images/menu_item/fish/СТЕЙК_СЕМГИ.webp",
    name: "Стейк семги",
    description:
      "Аппетитный стейк семги, приготовленный на гриле с нежной мякотью и интенсивным вкусом",
    price: "799",
    weight: "шт",
  },
  {
    id: 24,
    category: "5",
    categoryName: "РЫБА",
    img: "images/menu_item/fish/СИБАС.webp",
    name: "Форель",
    description:
      "Форель на гриле – свежая рыба с хрустящей коркой и нежным морским вкусом",
    price: "699",
    weight: "шт",
  },
  {
    id: 25,
    category: "6",
    categoryName: "ГАРНИР",
    img: "images/menu_item/garnish/ХАЧАПУРИ_НА_МАНГАЛЕ.webp",
    name: "Хачапури на мангале",
    description:
      "Интересное блюдо хачапури, готовящееся на мангале с сыром и ароматным тестом",
    price: "500",
    weight: "80г",
  },
  {
    id: 26,
    category: "6",
    categoryName: "ГАРНИР",
    img: "images/menu_item/garnish/ГРИБЫ.webp",
    name: "Грибы",
    description:
      "Шампиньоны на гриле – ароматные грибы с нежным вкусом и золотистой коркой",
    price: "190",
    weight: "80г",
  },
  {
    id: 27,
    category: "6",
    categoryName: "ГАРНИР",
    img: "images/menu_item/garnish/КАРТОШКА_НА_УГЛЯХ.webp",
    name: "Картошка на углях",
    description:
      "Ароматная картошка, запеченная на углях, с хрустящей коркой и нежным внутренним слоем",
    price: "100",
    weight: "100г",
  },
  {
    id: 28,
    category: "6",
    categoryName: "ГАРНИР",
    img: "images/menu_item/garnish/КАРТОШКА_С_КУРДЮКОМ.webp",
    name: "Картошка с курдюком",
    description:
      "Картошка, приготовленная с курдюком на гриле, сочная и ароматная",
    price: "160",
    weight: "100г",
  },
  {
    id: 29,
    category: "6",
    categoryName: "ГАРНИР",
    img: "images/menu_item/garnish/КАРТОШКА_С_САЛОМ.webp",
    name: "Картошка с салом",
    description:
      "Картошка с салом, приготовленная на гриле, сочетает аромат сала и хрустящей картошки",
    price: "130",
    weight: "100г",
  },
  {
    id: 30,
    category: "6",
    categoryName: "ГАРНИР",
    img: "images/menu_item/garnish/ОВОЩИ_НА_ МАНГАЛЕ.webp",
    name: "Овощи на мангале",
    description:
      "Сочные овощи, готовые на мангале, со вкусом копченых углей и ароматными специями",
    price: "350",
    weight: "300г",
  },
  {
    id: 31,
    category: "6",
    categoryName: "ГАРНИР",
    img: "images/menu_item/garnish/КАРТОШКА_С_ БЕКОНОМ.webp",
    name: "Картошка с беконом",
    description:
      "Картошка с беконом на гриле - сочетание хрустящей картошки и аромата обжаренного бекона",
    price: "350",
    weight: "230г",
  },
  {
    id: 32,
    category: "7",
    categoryName: "САЛАТ",
    img: "images/menu_item/Salad/ЦЕЗАРЬ.webp",
    name: "Цезарь с курицей",
    description:
      "Салат Цезарь с курицей - сочная куриная грудка и свежие листья с ароматным соусом",
    price: "350",
    weight: "300г",
  },
  {
    id: 33,
    category: "7",
    categoryName: "САЛАТ",
    img: "images/menu_item/Salad/ГРЕЧЕСКИЙ.webp",
    name: "Греческий",
    description:
      "Греческий салат - сочные огурцы, помидоры, фета и маслины в ароматном соусе",
    price: "399",
    weight: "300г",
  },
  {
    id: 34,
    category: "7",
    categoryName: "САЛАТ",
    img: "images/menu_item/Salad/СВЕЖИЕ_ОВОЩИ.webp",
    name: "Свежие овощи",
    description:
      "Салат из свежих овощей - красочное сочетание свежести и натуральных вкусов",
    price: "250",
    weight: "230г",
  },
  {
    id: 35,
    category: "7",
    categoryName: "САЛАТ",
    img: "images/menu_item/Salad/ХОРОВАЦ.webp",
    name: "Хоровац",
    description:
      "Салат Хоровац - вкусное сочетание огурцов, помидоров, лука и зелени с приправами",
    price: "320",
    weight: "300г",
  },
  {
    id: 36,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/ЛАВАШ.webp",
    name: "лаваш",
    description: "Белый хлеб в виде тонкой лепёшки",
    price: "30",
    weight: "шт",
  },
  {
    id: 37,
    category: "9",
    categoryName: "СОУС",
    img: "images/menu_item/sauce/ТОМАТНЫЙ.webp",
    name: "Томатный",
    description:
      "Томатный соус - классический, насыщенный и ароматный, идеально подходит для множества блюд",
    price: "50",
    weight: "шт",
  },
  {
    id: 38,
    category: "9",
    categoryName: "СОУС",
    img: "images/menu_item/sauce/ЧЕСНОЧНЫЙ.webp",
    name: "Чесночный",
    description:
      "Чесночный соус - насыщенный вкус чеснока, идеально подходит к различным блюдам",
    price: "50",
    weight: "шт",
  },
  {
    id: 39,
    category: "9",
    categoryName: "СОУС",
    img: "images/menu_item/sauce/ТЕРИЯКИ.webp",
    name: "Терияки",
    description:
      "Соус Терияки - сладкий и соленый соус, придающий блюдам неповторимый вкус и аромат",
    price: "100",
    weight: "шт",
  },
  {
    id: 40,
    category: "9",
    categoryName: "СОУС",
    img: "images/menu_item/sauce/НАШАРАБ.webp",
    name: "Нашараб",
    description:
      "Соус Нашараб - пикантное и ароматное сочетание специй, идеальное для мясных блюд",
    price: "100",
    weight: "шт",
  },
  {
    id: 41,
    category: "9",
    categoryName: "СОУС",
    img: "images/menu_item/sauce/ТКЕМАЛИ.webp",
    name: "Ткемали",
    description:
      "Ткемали соус - кисло-сладкий соус с ароматом сливы, популярный в грузинской кухне",
    price: "100",
    weight: "шт",
  },
  {
    id: 42,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/ЛЕПЕШКА.webp",
    name: "Лепешка",
    description:
      "Лепешка, приготовленная по классическому рецепту, отличается пресным вкусом",
    price: "50",
    weight: "шт",
  },
  {
    id: 43,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Сок_Добрый.webp",
    name: "Добрый яблоко",
    description: "",
    price: "50",
    weight: "0,2",
  },
  {
    id: 44,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Fanta.webp",
    name: "Фанта",
    description: "",
    price: "110",
    weight: "0,5",
  },
  {
    id: 45,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Coca-Cola.webp",
    name: "Кока-кола",
    description: "",
    price: "110",
    weight: "0,5",
  },
  {
    id: 46,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Чай_Lipton.webp",
    name: "Чай Липтон",
    description: "",
    price: "80",
    weight: "0,5",
  },
  {
    id: 47,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Adrenalin_rush.webp",
    name: "Адреналин Раш",
    description: "",
    price: "125",
    weight: "0,33",
  },
  {
    id: 48,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Adrenalin_rush.webp",
    name: "Адреналин Раш",
    description: "",
    price: "170",
    weight: "0,5",
  },
  {
    id: 49,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Aqua.webp",
    name: "Аква газ.",
    description: "",
    price: "50",
    weight: "0,5",
  },
  {
    id: 50,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Aqua_1.webp",
    name: "Аква",
    description: "",
    price: "50",
    weight: "0,5",
  },
  {
    id: 51,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Coca-Cola03.webp",
    name: "Кока-кола",
    description: "",
    price: "100",
    weight: "0,33",
  },
  {
    id: 52,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Pepsi03.webp",
    name: "Пепси",
    description: "",
    price: "100",
    weight: "0,33",
  },
  {
    id: 53,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/АСКАНИЯ.webp",
    name: "Аскания",
    description: "",
    price: "100",
    weight: "0,5",
  },
  {
    id: 54,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Лимонад.webp",
    name: "Натахтари",
    description: "",
    price: "150",
    weight: "0,5",
  },
  {
    id: 55,
    category: "a",
    categoryName: "НАПИТОК",
    img: "images/menu_item/drinks/Тархун.webp",
    name: "Тархун",
    description: "",
    price: "130",
    weight: "0,5",
  },
  {
    id: 56,
    category: "0",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/ШЕЙКА_СВИНАЯ.webp",
    name: "Свиная шейка",
    description:
      "Сочный и ароматный шашлык из свиной шейки, приготовленный на углях с нежными специями",
    price: "440",
    weight: "шп",
  },
  {
    id: 57,
    category: "0",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/БЕДРО_КУРИНЫЕ.webp",
    name: "Куриное бедро",
    description:
      "Сочный шашлык с куриным бедром, приготовленный с травами и ароматными специями",
    price: "350",
    weight: "шп",
  },
  {
    id: 58,
    category: "0",
    categoryName: "ШАШЛЫК",
    img: "images/menu_item/barbecue/МЯКОТЬ_БАРАНИНА.webp",
    name: "Мякоть баранина",
    description:
      "Изысканный шашлык из нежной мякоти баранины, приправленный ароматными специями и обжаренный на углях",
    price: "640",
    weight: "шп",
  },
  {
    id: 59,
    category: "0",
    categoryName: "ЛЮЛЯ-КЕБАБ",
    img: "images/menu_item/lula_kebab/ГОВЯДИНА.webp",
    name: "Говядина",
    description:
      "Изысканный люля-кебаб с нежной говядиной и оригинальными специями, приготовленный с любовью",
    price: "320",
    weight: "шп",
  },
  {
    id: 60,
    category: "0",
    categoryName: "ШАУРМА",
    img: "images/menu_item/shawarma/ШАУРМА_КУРИЦА.webp",
    name: "C курицей",
    description:
      "Аппетитная шаурма с нежным куриным мясом и ароматными специями в пышном лаваше",
    price: "200",
    weight: "шт",
  },
  {
    id: 61,
    category: "0",
    categoryName: "ГАРНИР",
    img: "images/menu_item/garnish/ХАЧАПУРИ_НА_МАНГАЛЕ.webp",
    name: "Хачапури на мангале",
    description:
      "Интересное блюдо хачапури, готовящееся на мангале с сыром и ароматным тестом",
    price: "450",
    weight: "80г",
  },
  {
    id: 62,
    category: "1",
    categoryName: "СЕТЫ",
    img: "images/menu_item/set/set.webp",
    name: "Сет из говядины и баранины",
    description:
      "3x корейка ягненка;\n2x филе телятины;\n2x мякоть баранина;\n3x ребра баранина;\n3x люля говядина;\n3x картошка с курдюком;\n2x овощи на мангале;\n2x лепешка;\n3x соус чесночный;\n3x соус томатный;",
    price: "8999",
    weight: "",
  },
  {
    id: 63,
    category: "1",
    categoryName: "СЕТЫ",
    img: "images/menu_item/set/5.webp",
    name: "Сет на 5 человек",
    description:
      "2x шейка;\n2x куриное филе;\n2x люля курица;\n2x люля свинина;\n2x картошка с салом;\n2x грибы;\n2x лепешка;\n2x соус чесночный;\n2x соус томатный;",
    price: "3699",
    weight: "",
  },
  {
    id: 64,
    category: "1",
    categoryName: "СЕТЫ",
    img: "images/menu_item/set/10.webp",
    name: "Сет на 10 человек",
    description:
      "5x шейка;\n2x куриное филе;\n2x куриное бедро;\n2x куриные крылья;\n3x люля курица;\n3x люля говядина;\n2x картошка на углях;\n2x овощи на мангале;\n2x грибы;\n3x лепешка;\n2x соус чесночный;\n2x соус томатный;",
    price: "7499",
    weight: "",
  },
  {
    id: 65,
    category: "1",
    categoryName: "СЕТЫ",
    img: "images/menu_item/set/15.webp",
    name: "Сет на 15 человек",
    description:
      "6x шейка;\n3x куриное филе;\n3x куриные крылья;\n3x куриное бедро;\n2x ребра баранина;\n2x люля курица;\n2x люля говядина;\n2x люля свинина;\n2x люля баранина;\n3x картошка на углях;\n3x овощи на мангале;\n3x грибы;\n3x лепешка;\n3x соус чесночный;\n3x соус томатный;",
    price: "10999",
    weight: "",
  },
  {
    id: 66,
    category: "1",
    categoryName: "СЕТЫ",
    img: "images/menu_item/set/20.webp",
    name: "Сет на 20 человек",
    description:
      "8x шейка;\n3x филе телятины;\n3x куриное филе;\n3x куриное бедро;\n3x куриные крылья;\n3x ребра баранина;\n3x люля курица;\n3x люля говядина;\n3x люля свинина;\n3x люля баранина;\n4x картошка на углях;\n3x овощи на мангале;\n3x грибы;\n5x лепешка;\n5x соус чесночный;\n5x соус томатный;",
    price: "15999",
    weight: "",
  },
  {
    id: 67,
    category: "7",
    categoryName: "САЛАТ",
    img: "images/menu_item/Salad/Тайский.webp",
    name: "Тайский",
    description:
      "Салат Тайский - пряный, хрустящий салат с сочными овощами и ароматными травами",
    price: "450",
    weight: "300г",
  },
  {
    id: 68,
    category: "7",
    categoryName: "САЛАТ",
    img: "images/menu_item/Salad/Светофор.webp",
    name: "Светофор",
    description:
      "Салат Тайский - пряный, хрустящий салат с сочными овощами и ароматными травами",
    price: "500",
    weight: "300г",
  },
  {
    id: 69,
    category: "7",
    categoryName: "САЛАТ",
    img: "images/menu_item/Salad/ОвощнойБукет.webp",
    name: "Овощной букет",
    description:
      "Салат Овощной букет - Свежий, хрустящий салат с яркими овощами, зеленью и легким соусом",
    price: "490",
    weight: "300г",
  },
  {
    id: 70,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/ОсетинскийПирогСырЗелень.webp",
    name: "Осетинский пирог сыр зелень",
    description:
      "Тонкий, румяный пирог с нежным сыром и ароматной зеленью внутри",
    price: "600",
    weight: "шт",
  },
  {
    id: 71,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/ОсетинскийПирогДесертный.webp",
    name: "Осетинский пирог десертный",
    description:
      "Нежный, сладкий пирог с фруктовой начинкой и золотистой хрустящей корочкой",
    price: "200",
    weight: "шт",
  },
  {
    id: 72,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/ХачапуриПоМегрельски.webp",
    name: "Хачапури по мегрельски",
    description:
      "Сырный, румяный хачапури с хрустящей корочкой и тянущейся сырной начинкой",
    price: "600",
    weight: "шт",
  },
  {
    id: 73,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/ХачапуриЖульен.webp",
    name: "Хачапури жульен",
    description:
      "Пышный хачапури, наполненный сливочным жульеном с грибами и растекающимся сыром",
    price: "550",
    weight: "шт",
  },
  {
    id: 74,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/ХачапуриПоИмеретински.webp",
    name: "Хачапури по-имеретински",
    description:
      "Классический круглый хачапури с нежной, тянущейся сырной начинкой внутри мягкого теста",
    price: "550",
    weight: "шт",
  },
  {
    id: 75,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/ХачапуриПоАджарски.webp",
    name: "Хачапури по-аджарски",
    description:
      "Лодочка из румяного теста, наполненная расплавленным сыром, с яйцом и маслом",
    price: "500",
    weight: "шт",
  },
  {
    id: 76,
    category: "8",
    categoryName: "МУЧНОЕ",
    img: "images/menu_item/bakery/Хинкали.webp",
    name: "Хинкали",
    description: "Сочные пельмени с пряным мясным фаршем и бульоном внутри.",
    price: "100",
    weight: "шт",
  },
];
